version: '3'

services:
  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus-go-basic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  mongodb_data:
  redis_data:
