// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type MoviesOnlineAccount struct {
	ID        int32
	Firstname sql.NullString
	Lastname  sql.NullString
	Login     sql.NullString
	Password  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MoviesOnlineEpisode struct {
	ID               int32
	Quality          sql.NullString
	Rating           sql.NullFloat64
	ProductionPeriod sql.NullString
	SerialID         sql.NullInt32
	SeasonID         sql.NullInt32
	Sort             sql.NullInt32
	Active           sql.NullString
	FileID           sql.NullInt32
	Title            sql.NullString
	Duration         sql.NullFloat64
	Description      sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type MoviesOnlineSeason struct {
	ID        int32
	SerialID  sql.NullInt32
	Sort      sql.NullInt32
	Active    sql.NullString
	Title     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MoviesOnlineSerial struct {
	ID               int32           `json:"id"`
	Sort             sql.NullInt32   `json:"sort"`
	Active           sql.NullString  `json:"active"`
	FileID           sql.NullInt32   `json:"fileID"`
	Title            sql.NullString  `json:"title"`
	ProductionPeriod sql.NullString  `json:"productionPeriod"`
	Rating           sql.NullFloat64 `json:"rating"`
	Quality          sql.NullString  `json:"quality"`
	Duration         sql.NullFloat64 `json:"duration"`
	Description      sql.NullString  `json:"description"`
	CreatedAt        time.Time       `json:"createdAt"`
	UpdatedAt        time.Time       `json:"updatedAt"`
}
