// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/grpc/v1/serial.proto

package serial_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Serial struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FileId           int64                  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Rating           float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Duration         float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Sort             int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	ProductionPeriod string                 `protobuf:"bytes,8,opt,name=production_period,json=productionPeriod,proto3" json:"production_period,omitempty"`
	Quality          string                 `protobuf:"bytes,9,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Serial) Reset() {
	*x = Serial{}
	mi := &file_api_grpc_v1_serial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Serial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Serial) ProtoMessage() {}

func (x *Serial) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_serial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Serial.ProtoReflect.Descriptor instead.
func (*Serial) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_serial_proto_rawDescGZIP(), []int{0}
}

func (x *Serial) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Serial) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Serial) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *Serial) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Serial) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Serial) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Serial) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Serial) GetProductionPeriod() string {
	if x != nil {
		return x.ProductionPeriod
	}
	return ""
}

func (x *Serial) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type CreateSerialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	FileId           int64                  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Rating           float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Duration         float64                `protobuf:"fixed64,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Sort             int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	ProductionPeriod string                 `protobuf:"bytes,7,opt,name=production_period,json=productionPeriod,proto3" json:"production_period,omitempty"`
	Quality          string                 `protobuf:"bytes,8,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSerialRequest) Reset() {
	*x = CreateSerialRequest{}
	mi := &file_api_grpc_v1_serial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSerialRequest) ProtoMessage() {}

func (x *CreateSerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_serial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSerialRequest.ProtoReflect.Descriptor instead.
func (*CreateSerialRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_serial_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSerialRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSerialRequest) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *CreateSerialRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSerialRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateSerialRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateSerialRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateSerialRequest) GetProductionPeriod() string {
	if x != nil {
		return x.ProductionPeriod
	}
	return ""
}

func (x *CreateSerialRequest) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

type SerialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialRequest) Reset() {
	*x = SerialRequest{}
	mi := &file_api_grpc_v1_serial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialRequest) ProtoMessage() {}

func (x *SerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_serial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialRequest.ProtoReflect.Descriptor instead.
func (*SerialRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_serial_proto_rawDescGZIP(), []int{2}
}

func (x *SerialRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SerialList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serials       []*Serial              `protobuf:"bytes,1,rep,name=serials,proto3" json:"serials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialList) Reset() {
	*x = SerialList{}
	mi := &file_api_grpc_v1_serial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialList) ProtoMessage() {}

func (x *SerialList) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_serial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialList.ProtoReflect.Descriptor instead.
func (*SerialList) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_serial_proto_rawDescGZIP(), []int{3}
}

func (x *SerialList) GetSerials() []*Serial {
	if x != nil {
		return x.Serials
	}
	return nil
}

var File_api_grpc_v1_serial_proto protoreflect.FileDescriptor

const file_api_grpc_v1_serial_proto_rawDesc = "" +
	"\n" +
	"\x18api/grpc/v1/serial.proto\x12\x06serial\x1a\x1bgoogle/protobuf/empty.proto\"\xf8\x01\n" +
	"\x06Serial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\x03R\x06fileId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\x12+\n" +
	"\x11production_period\x18\b \x01(\tR\x10productionPeriod\x12\x18\n" +
	"\aquality\x18\t \x01(\tR\aquality\"\xf5\x01\n" +
	"\x13CreateSerialRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\x03R\x06fileId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x01R\bduration\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12+\n" +
	"\x11production_period\x18\a \x01(\tR\x10productionPeriod\x12\x18\n" +
	"\aquality\x18\b \x01(\tR\aquality\"\x1f\n" +
	"\rSerialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"6\n" +
	"\n" +
	"SerialList\x12(\n" +
	"\aserials\x18\x01 \x03(\v2\x0e.serial.SerialR\aserials2\xb6\x02\n" +
	"\rSerialService\x12=\n" +
	"\fCreateSerial\x12\x1b.serial.CreateSerialRequest\x1a\x0e.serial.Serial\"\x00\x124\n" +
	"\tGetSerial\x12\x15.serial.SerialRequest\x1a\x0e.serial.Serial\"\x00\x120\n" +
	"\fUpdateSerial\x12\x0e.serial.Serial\x1a\x0e.serial.Serial\"\x00\x12?\n" +
	"\fDeleteSerial\x12\x15.serial.SerialRequest\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\rGetAllSerials\x12\x16.google.protobuf.Empty\x1a\x12.serial.SerialList\"\x00B\x18Z\x16pkg/grpc/v1/serial_apib\x06proto3"

var (
	file_api_grpc_v1_serial_proto_rawDescOnce sync.Once
	file_api_grpc_v1_serial_proto_rawDescData []byte
)

func file_api_grpc_v1_serial_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_serial_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_serial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_v1_serial_proto_rawDesc), len(file_api_grpc_v1_serial_proto_rawDesc)))
	})
	return file_api_grpc_v1_serial_proto_rawDescData
}

var file_api_grpc_v1_serial_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_v1_serial_proto_goTypes = []any{
	(*Serial)(nil),              // 0: serial.Serial
	(*CreateSerialRequest)(nil), // 1: serial.CreateSerialRequest
	(*SerialRequest)(nil),       // 2: serial.SerialRequest
	(*SerialList)(nil),          // 3: serial.SerialList
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
}
var file_api_grpc_v1_serial_proto_depIdxs = []int32{
	0, // 0: serial.SerialList.serials:type_name -> serial.Serial
	1, // 1: serial.SerialService.CreateSerial:input_type -> serial.CreateSerialRequest
	2, // 2: serial.SerialService.GetSerial:input_type -> serial.SerialRequest
	0, // 3: serial.SerialService.UpdateSerial:input_type -> serial.Serial
	2, // 4: serial.SerialService.DeleteSerial:input_type -> serial.SerialRequest
	4, // 5: serial.SerialService.GetAllSerials:input_type -> google.protobuf.Empty
	0, // 6: serial.SerialService.CreateSerial:output_type -> serial.Serial
	0, // 7: serial.SerialService.GetSerial:output_type -> serial.Serial
	0, // 8: serial.SerialService.UpdateSerial:output_type -> serial.Serial
	4, // 9: serial.SerialService.DeleteSerial:output_type -> google.protobuf.Empty
	3, // 10: serial.SerialService.GetAllSerials:output_type -> serial.SerialList
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_serial_proto_init() }
func file_api_grpc_v1_serial_proto_init() {
	if File_api_grpc_v1_serial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_v1_serial_proto_rawDesc), len(file_api_grpc_v1_serial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_serial_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_serial_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_serial_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_serial_proto = out.File
	file_api_grpc_v1_serial_proto_goTypes = nil
	file_api_grpc_v1_serial_proto_depIdxs = nil
}
